#! /usr/bin/env bash

# Build this example for multiple targets

set -ex

rm -rf .build
TARGET=XCORE-AI-EXPLORER xmake
rm -rf .build  # need to delete between each target because xmake doesn't 
               # seem to support having different TARGET for the same app
TARGET=XCORE-200-EXPLORER xmake
rm -rf .build
